- name: Check optional args
  run_once: true
  delegate_to: localhost
  ansible.builtin.set_fact:
    daemon_user: "{{ daemon_user | default('cosmovisor') }}"
- name: Check service manager
  run_once: true
  delegate_to: localhost
  ansible.builtin.assert:
    that: ansible_facts.service_mgr in service_mgr_choices
    fail_msg: "'{{ ansible_facts.service_mgr }}' not supported, choices: {{ service_mgr_choices }}"
  vars:
    service_mgr_choices: ['runit']
- name: Check parameter 'state'
  run_once: true
  delegate_to: localhost
  ansible.builtin.assert:
    that: state in state_choices
    fail_msg: "'{{ state }}' not supported, choices: {{ state_choices }}"
  vars:
    state_choices: ['absent', 'latest', 'present']
- name: Decide whether works needed or not
  ansible.builtin.include_tasks:
    file: "{{ ansible_facts.service_mgr }}/decision.yml"
- name: Execute {{ ansible_facts.service_mgr }} specific tasks
  ansible.builtin.include_tasks:
    file: "{{ ansible_facts.service_mgr }}/{{ state }}.yml"
- name: Execute common tasks
  ansible.builtin.include_tasks:
    file: common/{{ state }}.yml
