- name: Copy genesis
  ansible.builtin.copy:
    src: "{{ artifact.path }}/genesis.json"
    dest: "{{ daemon_home }}/config/genesis.json"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: preserve
- name: Set local facts
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.file', ([artifact.path, 'genesis.json'] | join('/'))) | ansible.builtin.password_hash('sha512') }}"
    dest: /etc/ansible/facts.d/genesis.fact
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rw,g=r,o=r
- name: Export genesis
  when: dest is defined
  run_once: true
  delegate_to: localhost
  ansible.builtin.copy:
    remote_src: true
    src: "{{ artifact.path }}/genesis.json"
    dest: "{{ dest }}"
    mode: preserve
