- name: Copy gentxs
  ansible.builtin.copy:
    src: "{{ gentx }}/"
    dest: "{{ work.path }}/gentx"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: preserve
- name: Prepare genesis script
  ansible.builtin.template:
    src: generate.sh.j2
    dest: "{{ work.path }}/generate.sh"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rw,g=r,o=r
- name: Generate genesis
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    cmd: sh generate.sh
    chdir: "{{ work.path }}"
