- name: Gather local facts (cosmovisor)
  ansible.builtin.set_fact:
    user: "{{ ansible_local.cosmovisor.user }}"
    daemon_name: "{{ ansible_local.cosmovisor.daemon_name }}"
    daemon_home: "{{ ansible_local.cosmovisor.daemon_home }}"
- name: Gather local facts (daemon)
  ansible.builtin.set_fact:
    region_id: "{{ ansible_local.daemon.region_id }}"
    chain_id: "{{ ansible_local.daemon.chain_id }}"
- name: Create facts directory
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rwx,g=rx,o=rx
- name: Set work directory
  ansible.builtin.tempfile:
    state: directory
  register: work
- name: Create work directory
  ansible.builtin.file:
    path: "{{ work.path }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rwx,g=rx,o=rx
- name: Execute phase specific works
  ansible.builtin.include_tasks:
    file: "{{ phase }}.yml"
- name: Remove work directory
  ansible.builtin.file:
    path: "{{ work.path }}"
    state: absent
