- name: Gather local facts (cosmovisor)
  ansible.builtin.set_fact:
    user: "{{ ansible_local.cosmovisor.user }}"
    daemon_name: "{{ ansible_local.cosmovisor.daemon_name }}"
    daemon_home: "{{ ansible_local.cosmovisor.daemon_home }}"
- name: Gather local facts (daemon)
  ansible.builtin.set_fact:
    region_id: "{{ ansible_local.daemon.region_id }}"
    chain_id: "{{ ansible_local.daemon.chain_id }}"
- name: Create facts directory
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rwx,g=rx,o=rx
- name: Find existing genesis
  run_once: true
  delegate_to: validator
  ansible.builtin.stat:
    path: "{{ daemon_home }}/config/genesis.json"
  register: genesis
- name: Export genesis
  when:
  - dest is defined
  - genesis.stat.exists
  run_once: true
  delegate_to: validator
  ansible.builtin.fetch:
    src: "{{ daemon_home }}/config/genesis.json"
    flat: true
    dest: "{{ dest }}"
- name: End play if no works needed
  when: genesis.stat.exists
  ansible.builtin.meta: end_play
- name: Create artifact directory
  run_once: true
  delegate_to: localhost
  ansible.builtin.tempfile:
    state: directory
  register: artifact
- name: Set work directory
  ansible.builtin.tempfile:
    state: directory
  register: work
- name: Create work directory
  ansible.builtin.file:
    path: "{{ work.path }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rwx,g=rx,o=rx
- name: Generate gentx
  when: type == "seat"
  ansible.builtin.include_tasks:
    file: generate-gentx.yml
- name: Collect gentxs and generate genesis
  when: type == "validator"
  ansible.builtin.include_tasks:
    file: collect-gentxs.yml
- name: Export genesis
  when: dest is defined
  run_once: true
  delegate_to: validator
  ansible.builtin.fetch:
    src: "{{ daemon_home }}/config/genesis.json"
    flat: true
    dest: "{{ dest }}"
- name: Remove work directory
  ansible.builtin.file:
    path: "{{ work.path }}"
    state: absent
- name: Remove artifact directory
  run_once: true
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ artifact.path }}"
    state: absent
