- name: Gather local facts (cosmovisor)
  ansible.builtin.set_fact:
    user: "{{ ansible_local.cosmovisor.user }}"
    daemon_name: "{{ ansible_local.cosmovisor.daemon_name }}"
    daemon_home: "{{ ansible_local.cosmovisor.daemon_home }}"
- name: Gather local facts (daemon)
  ansible.builtin.set_fact:
    region_id: "{{ ansible_local.daemon.region_id }}"
    chain_id: "{{ ansible_local.daemon.chain_id }}"
- name: Prohibit override
  ansible.builtin.assert:
    that: src is undefined or hostvars.validator.ansible_local.genesis is undefined
    fail_msg: "hello will override existing genesis"
- name: Create facts directory
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rwx,g=rx,o=rx
- name: Create artifact directory
  run_once: true
  delegate_to: localhost
  ansible.builtin.tempfile:
    state: directory
  register: artifact
- name: Set work directory
  ansible.builtin.tempfile:
    state: directory
  register: work
- name: Create work directory
  ansible.builtin.file:
    path: "{{ work.path }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rwx,g=rx,o=rx
- name: Use external genesis
  when: src is defined
  run_once: true
  delegate_to: localhost
  ansible.builtin.copy:
    remote_src: true
    src: "{{ src }}"
    dest: "{{ artifact.path }}/genesis.json"
    mode: u=rw,g=r,o=r
- name: Use existing genesis
  when:
  - type == 'validator'
  - ansible_local.genesis is defined
  ansible.builtin.fetch:
    src: "{{ daemon_home }}/config/genesis.json"
    dest: "{{ artifact.path }}/"
    mode: preserve
- name: Generate gentx
  when:
  - type == "seat"
  - src is undefined
  - hostvars.validator.ansible_local.genesis is undefined
  ansible.builtin.include_tasks:
    file: generate-gentx.yml
- name: Collect gentxs and generate genesis
  when:
  - type == "validator"
  - src is undefined
  - ansible_local.genesis is undefined
  ansible.builtin.include_tasks:
    file: collect-gentxs.yml
- name: Distribute genesis
  ansible.builtin.include_tasks:
    file: distribute-genesis.yml
- name: Remove work directory
  ansible.builtin.file:
    path: "{{ work.path }}"
    state: absent
- name: Remove artifact directory
  run_once: true
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ artifact.path }}"
    state: absent
