- name: Gather local facts (cosmovisor)
  ansible.builtin.set_fact:
    user: "{{ ansible_local.cosmovisor.user }}"
    daemon_name: "{{ ansible_local.cosmovisor.daemon_name }}"
    daemon_home: "{{ ansible_local.cosmovisor.daemon_home }}"
- name: Create artifact directory
  run_once: true
  delegate_to: localhost
  ansible.builtin.tempfile:
    state: directory
  register: artifact
- name: Set work directory
  ansible.builtin.tempfile:
    state: directory
  register: work
- name: Create work directory
  ansible.builtin.file:
    path: "{{ work.path }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rwx,g=rx,o=rx
- name: Prepare the script
  ansible.builtin.template:
    src: add.sh.j2
    dest: "{{ work.path }}/add.sh"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rwx,g=rx,o=rx
- name: Add key
  when: type == "seat"
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    cmd: ./add.sh
    chdir: "{{ work.path }}"
- name: Remove work directory
  ansible.builtin.file:
    path: "{{ work.path }}"
    state: absent
- name: Remove artifact directory
  run_once: true
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ artifact.path }}"
    state: absent
