FROM golang:bullseye

ARG workdir=/tmp/workdir

# Set working directory for the build
WORKDIR $workdir

# Add source files
COPY . ./

# make a bundle
RUN BUILDDIR=$(realpath $(mktemp -dp .)) && \
    BUILDDIR=$BUILDDIR CGO_ENABLED=0 make build && \
    cd $BUILDDIR && \
    tar -czf ../bundle.tar.gz @DAEMON_NAME@
