- name: Gather validator information
  ansible.builtin.set_fact:
    validator:
      node_id: "{{ hostvars.validator.ansible_local.daemon.node_id }}"
      private_ip: "{{ hostvars.validator.ansible_local.config.private_ip }}"
- name: Push seeds information
  ansible.builtin.copy:
    src: artifact/seeds/
    dest: "{{ work.path }}/seeds/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: preserve
- name: Prepare apply script
  ansible.builtin.template:
    src: apply.sh.j2
    dest: "{{ work.path }}/apply.sh"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rw,g=r,o=r
- name: Apply dynamic configs
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    cmd: sh apply.sh
    chdir: "{{ work.path }}"
