- name: Prepare gather script
  ansible.builtin.template:
    src: gather.sh.j2
    dest: "{{ work.path }}/gather.sh"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rw,g=r,o=r
- name: Gather dynamic information
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    cmd: sh gather.sh
    chdir: "{{ work.path }}"
- name: Fetch seed ip information
  when: type == "seed"
  ansible.builtin.fetch:
    src: /etc/ansible/facts.d/config.fact
    flat: true
    dest: artifact/{{ inventory_hostname }}/
- name: Fetch node id
  when: type == "seed"
  ansible.builtin.fetch:
    src: /etc/ansible/facts.d/daemon.fact
    flat: true
    dest: artifact/{{ inventory_hostname }}/
