- name: Remove service user
  ansible.builtin.user:
    user: "{{ daemon_user }}"
    state: absent
- name: Uninstall binary
  ansible.builtin.file:
    dest: /usr/local/bin/cosmovisor
    state: absent
