argument_specs:
  main:
    short_description: The main entry point for the gentx role.
    options:
      dest:
        type: path
        required: true
        description: The path of the generated gentx.
      operator:
        required: true
        description: The name of the operator in the keyring.
      bond_denom:
        default: atom
        description: The bond denom of the chain.
      delegation:
        type: int
        default: 1000000
        description: The delegation of the validators.
