- name: Push genesis information
  when: type == "validator"
  ansible.builtin.copy:
    src: artifact/genesis/
    dest: "{{ work.path }}/genesis/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rw,g=r,o=r
- name: Prepare gentx script
  when: type == "validator"
  ansible.builtin.template:
    src: collect-gentx.sh.j2
    dest: "{{ work.path }}/collect-gentx.sh"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rwx,g=rx,o=rx
- name: Collect gentx
  when: type == "validator"
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell:
    cmd: ./collect-gentx.sh
    chdir: "{{ work.path }}"
- name: Fetch genesis
  when: type == "validator"
  ansible.builtin.fetch:
    src: "{{ work.path }}/genesis/genesis.json"
    flat: true
    dest: artifact/genesis/
