name: cosmos-sdk rolling upgrades
on:
  pull_request:
    branches:
    - main
  schedule:
  - cron: '0 18 * * *'
jobs:
  rolling-upgrade-0_44:
    name: Rolling upgrade between 0.44 patches
    uses: ./.github/workflows/rolling.yml
    with:
      app-name: cosmos-sdk
      major-version: 0
      minor-version: 44
      patch-versions: "[4, 8]"
  rolling-upgrade-0_45:
    name: Rolling upgrade between 0.45 patches
    uses: ./.github/workflows/rolling.yml
    with:
      app-name: cosmos-sdk
      major-version: 0
      minor-version: 45
      patch-versions: "[0, 4, 8, 12, 16]"
  rolling-upgrade-0_46:
    name: Rolling upgrade between 0.46 patches
    uses: ./.github/workflows/rolling.yml
    with:
      app-name: cosmos-sdk
      major-version: 0
      minor-version: 46
      patch-versions: "[0, 4, 8, 12, 15]"
  rolling-upgrade-0_47:
    name: Rolling upgrade between 0.47 patches
    uses: ./.github/workflows/rolling.yml
    with:
      app-name: cosmos-sdk
      major-version: 0
      minor-version: 47
      patch-versions: "[0, 4, 5]"
