name: cosmos/cosmos-sdk rolling updates
on:
  pull_request:
    branches:
    - main
  schedule:
  - cron: '0 17 * * *'
jobs:
  cosmos-cosmos-sdk-rolling:
    name: cosmos/cosmos-sdk rolling updates
    strategy:
      max-parallel: 1
      matrix:
        include:
        - old-version: 0.44.4
          new-version: 0.44.8
        - old-version: 0.45.9
          new-version: 0.45.16
        - old-version: 0.46.7
          new-version: 0.46.15
        - old-version: 0.47.0
          new-version: 0.47.5
    uses: ./.github/workflows/rolling.yml
    with:
      app: cosmos/cosmos-sdk
      old-version: ${{ matrix.old-version }}
      new-version: ${{ matrix.new-version }}
