name: gaia in-place migrations
on:
  pull_request:
    branches:
    - main
  schedule:
  - cron: '0 20 * * *'
jobs:
  gaia-in-place:
    name: gaia in-place migrations
    strategy:
      max-parallel: 1
      matrix:
        include:
        - upgrade-name: v7-Theta
          old-version: 6.0.4
          new-version: 7.1.1
        - upgrade-name: v8-Rho
          old-version: 7.1.1
          new-version: 8.0.1
        - upgrade-name: v9-Lambda
          old-version: 8.0.1
          new-version: 9.1.1
        - upgrade-name: v10
          old-version: 9.1.1
          new-version: 10.0.2
        - upgrade-name: v11
          old-version: 10.0.2
          new-version: 11.0.0
        - upgrade-name: v12
          old-version: 11.0.0
          new-version: 12.0.0
    uses: ./.github/workflows/in-place.yml
    with:
      app-name: gaia
      upgrade-name: ${{ matrix.upgrade-name }}
      old-version: ${{ matrix.old-version }}
      new-version: ${{ matrix.new-version }}
