name: cosmos/gaia rolling updates
on:
  pull_request:
    branches:
    - main
  schedule:
  - cron: '0 18 1/2 * *'
jobs:
  cosmos-gaia-rolling:
    name: cosmos/gaia rolling updates
    strategy:
      max-parallel: 1
      matrix:
        include:
        - old-version: 6.0.3
          new-version: 6.0.4
        - old-version: 7.0.0
          new-version: 7.0.3
        - old-version: 7.1.0
          new-version: 7.1.1
        - old-version: 8.0.0
          new-version: 8.0.1
        - old-version: 9.0.0
          new-version: 9.0.3
        - old-version: 9.1.0
          new-version: 9.1.1
        - old-version: 10.0.0
          new-version: 10.0.2
    uses: ./.github/workflows/rolling.yml
    with:
      app: cosmos/gaia
      old-version: ${{ matrix.old-version }}
      new-version: ${{ matrix.new-version }}
