name: gaia rolling upgrades
on:
  pull_request:
    branches:
    - main
  schedule:
  - cron: '0 19 * * *'
jobs:
  gaia-rolling:
    name: gaia rolling updates
    strategy:
      matrix:
        include:
        - old-version: 6.0.3
          new-version: 6.0.4
        - old-version: 7.0.0
          new-version: 7.0.3
        - old-version: 7.1.0
          new-version: 7.1.1
        - old-version: 8.0.0
          new-version: 8.0.1
        - old-version: 9.0.0
          new-version: 9.0.3
        - old-version: 9.1.0
          new-version: 9.1.1
        - old-version: 10.0.0
          new-version: 10.0.2
    uses: ./.github/workflows/rolling.yml
    with:
      app-name: gaia
      old-version: ${{ matrix.old-version }}
      new-version: ${{ matrix.new-version }}
