name: cosmos/gaia in-place migrations
on:
  pull_request:
    branches:
    - main
  schedule:
  - cron: '0 20 * * *'
jobs:
  cosmos-gaia-in-place:
    name: cosmos/gaia in-place migrations
    strategy:
      max-parallel: 1
      matrix:
        include:
        - old-version: 6.0.4
          new-version: 7.1.1
        - old-version: 7.1.1
          new-version: 8.0.1
        - old-version: 8.0.1
          new-version: 9.1.1
        - old-version: 9.1.1
          new-version: 10.0.2
        - old-version: 10.0.2
          new-version: 11.0.0
        - old-version: 11.0.0
          new-version: 12.0.0
    uses: ./.github/workflows/in-place.yml
    with:
      app: cosmos/gaia
      old-version: ${{ matrix.old-version }}
      new-version: ${{ matrix.new-version }}
