name: gaia in-place migrations
on:
  pull_request:
    branches:
    - main
  schedule:
  - cron: '0 18 * * *'
jobs:
  in-place-migration-6_0_4-7_0_0:
    name: In-place migration from 6.0.4 to 7.0.0
    uses: ./.github/workflows/in-place.yml
    with:
      app-name: gaia
      upgrade-name: v7-Theta
      old-version: 6.0.4
      new-version: 7.0.0
  in-place-migration-7_1_1-8_0_0:
    name: In-place migration from 7.1.1 to 8.0.0
    uses: ./.github/workflows/in-place.yml
    with:
      app-name: gaia
      upgrade-name: v8-Rho
      old-version: 7.1.1
      new-version: 8.0.0
  in-place-migration-8_0_1-9_0_0:
    name: In-place migration from 8.0.0 to 9.0.0
    uses: ./.github/workflows/in-place.yml
    with:
      app-name: gaia
      upgrade-name: v9-Lambda
      old-version: 8.0.1
      new-version: 9.0.0
  in-place-migration-9_1_1-10_0_0:
    name: In-place migration from 9.1.1 to 10.0.0
    uses: ./.github/workflows/in-place.yml
    with:
      app-name: gaia
      upgrade-name: v10
      old-version: 9.1.1
      new-version: 10.0.0
  # in-place-migration-10_0_2-11_0_0:
  #   name: In-place migration from 10.0.2 to 11.0.0
  #   uses: ./.github/workflows/in-place.yml
  #   with:
  #     app-name: gaia
  #     old-version: 10.0.2
  #     new-version: 11.0.0
