name: In-place migration between versions
on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      upgrade-name:
        required: true
        type: string
      old-version:
        required: true
        type: string
      new-version:
        required: true
        type: string
defaults:
  run:
    shell: sh
jobs:
  in-place:
    name: In-place migration from ${{ inputs.old-version }} to ${{ inputs.new-version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: cmake -S . -B build -DAPP_NAME=${{ inputs.app-name }} -DFIXTURE_CHAIN_UPGRADE_NAME=${{ inputs.upgrade-name }} -DFIXTURE_DAEMON_VERSION=${{ inputs.old-version }} -DFIXTURE_NEW_DAEMON_VERSION=${{ inputs.new-version }}
    - name: Test
      run: VERBOSE=1 ctest --test-dir build --output-on-failure -R 'upgrade_chain_(auto|manual)'
