name: In-place migration between versions
on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      old-version:
        required: true
        type: string
      new-version:
        required: true
        type: string
defaults:
  run:
    shell: sh
jobs:
  in-place:
    name: from ${{ inputs.old-version }} to ${{ inputs.new-version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: cmake -S . -B build -DAPP=${{ inputs.app }} -DFIXTURE_APP_VERSION=${{ inputs.old-version }} -DFIXTURE_NEW_APP_VERSION=${{ inputs.new-version }} -DTEST_TIMEOUT=30m
    - name: Test
      run: VERBOSE=1 ctest --test-dir build --output-on-failure -R solo_inplace
