argument_specs:
  main:
    short_description: The main entry point for the genesis role.
    options:
      phase:
        required: true
        choices:
        - generate
        - collect
        - distribute
        description: The phase of the genesis generation.
      state_bond_denom:
        default: atom
        description: The bond denom of the chain.
      state_balance:
        type: int
        default: 1000000000
        description: The balance of the genesis users.
      state_delegation:
        type: int
        default: 1000000
        description: The delegation of the validators.
      state_unbonding_time:
        default: 10s
        description: The unbonding time of the chain.
      state_min_deposit:
        type: int
        default: 1
        description: The min deposit of the chain.
      state_voting_period:
        default: 10s
        description: The voting period of the chain.
